# --- Defaults ---
# --- pymarl options ---
runner: "episode" # Runs 1 env for an episode
mac: "basic_mac" # Basic controller
env: "sc2" # Environment name
## ADDED ##
algo_name: "qmix"
run_script: "run_default"
transfer: False
###

env_args: {} # Arguments for the environment
batch_size_run: 1 # Number of environments to run in parallel
test_interval: 50000 # Test after {} timesteps have passed
test_greedy: True # Use greedy evaluation (if False, will set epsilon floor to 0
log_interval: 50000 # Log summary of stats after every {} timesteps
runner_log_interval: 50000 # Log runner stats (not test stats) every {} timesteps
learner_log_interval: 50000 # Log training stats every {} timesteps
t_max: 10050000 # Stop running after this many timesteps
use_cuda: True # Use gpu by default unless it isn't available
buffer_cpu_only: True # If true we won't keep all of the replay buffer in vram

# --- Logging options ---
use_tensorboard: True # Log results to tensorboard
save_model: True # Save the models to disk
save_model_interval: 1000000 # Save models after this many timesteps

evaluate: True # Evaluate model for test_nepisode episodes and quit (no training)
save_eval_traj: True # save eval episodes to local_results_path
test_nepisode: 8008 # Number of episodes to test for
epsilon_start: 0.05 # manually set epsilon! 
epsilon_finish: 0.05
# Load a checkpoint from this path
checkpoint_path: "/scratch/cluster/clw4542/marl_results/qmix_8v9/models/qmix_sc2_baseline__seed=112358_07-27-16-54-39/"

# "/scratch/cluster/clw4542/marl_results/qmix_3sv4z/models/qmix_sc2_baseline-fc=2__seed=112358_01-23-20-42-41"
# "/scratch/cluster/clw4542/marl_results/qmix_8v9/models/qmix_sc2_baseline__seed=112358_07-27-16-54-39/"
# "/scratch/cluster/clw4542/marl_results/qmix_3sv5z/models/qmix_sc2_baseline__seed=112358_07-27-16-59-44"
# "/scratch/cluster/clw4542/marl_results/qmix_3sv3z/models/qmix_sc2_baseline__seed=112358_07-27-16-58-06"
# "/scratch/cluster/clw4542/marl_results/qmix_3sv4z/models/qmix_sc2_baseline-fc=2__seed=112358_01-23-20-42-41"
# "/scratch/cluster/clw4542/marl_results/qmix_5v6/models/qmix_sc2_baseline-fc=2-buffer=5000__seed=112358_01-22-20-53-57" 

load_step: 0 # Load model trained on this many timesteps (0 if choose max possible)

save_replay: False # Saving the replay of the model loaded from checkpoint_path
local_results_path: "/scratch/cluster/clw4542/marl_results/qmix_8v9" # Path for local results

# --- RL hyperparameters ---
gamma: 0.99
batch_size: 32 # Number of episodes to train on
buffer_size: 8008 # Size of the replay buffer
lr: 0.0005 # Learning rate for agents
critic_lr: 0.0005 # Learning rate for critics
optim_alpha: 0.99 # RMSProp alpha
optim_eps: 0.00001 # RMSProp epsilon
grad_norm_clip: 10 # Reduce magnitude of gradients above this L2 norm

# --- Agent parameters ---
agent: "rnn" # Default rnn agent
rnn_hidden_dim: 64 # Size of hidden state for default rnn agent
obs_agent_id: True # Include the agent's one_hot id in the observation
obs_last_action: True # Include the agent's last action (one_hot) in the observation

# --- Experiment running params ---
repeat_id: 1
label: "saved_data=8008_eval-only_eps=0.05"
# label: "saved_data=5005_eval-only_eps=0.025" # "baseline"